=== awesome-nfv/un-orchestrator/name-resolver/config/network-functions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

<!-- definition of attributes -->
<xsd:attribute name="name">
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="([a-z]|[A-Z]|[0-9]|_|-)+"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>

<xsd:attribute name="location">	
	<xsd:simpleType>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="local" />
			<xsd:enumeration value="remote" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:attribute>

<!-- definition of types -->

<xsd:complexType name="implementationType">
	<xsd:attribute name="uri" type="xsd:string" use="required"/>
</xsd:complexType>


<!-- definition of elements -->
<xsd:element name="network-functions">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="network-function" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:choice minOccurs="1" maxOccurs="unbounded">
						<xsd:element name="docker" type="implementationType"/>
						<xsd:element name="kvm" type="implementationType"/>	
						<xsd:element name="dpdk">
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:extension base="implementationType">
										<xsd:attribute name="cores" type="xsd:string" use="required"/>
										<xsd:attribute ref="location" use="required"/>
									</xsd:extension>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>
						<xsd:element name="native">
							<xsd:complexType>
								<xsd:complexContent>
									<xsd:extension base="implementationType">
										<xsd:attribute ref="location" use="required"/>
										<xsd:attribute name="dependencies" type="xsd:string" use="required"/>
									</xsd:extension>
								</xsd:complexContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:choice>
					<xsd:attribute ref="name" use="required"/>
					<!-- TODO: put num-ports mandatory! -->
					<xsd:attribute name="num-ports" type="xsd:integer"/>
					<xsd:attribute name="summary" type="xsd:string" use="required"/>
				</xsd:complexType>
			</xsd:element> 
		</xsd:sequence>
	</xsd:complexType>
	<xsd:unique name="unique-network-function">
		<xsd:selector xpath="network-functions/network-function" />
		<xsd:field xpath="@name" />
	</xsd:unique>
</xsd:element>


</xsd:schema>

=== awesome-nfv/un-orchestrator/use-cases/frog/name_resolver_conf.xml
<?xml version="1.0" encoding="UTF-8"?>

<network-functions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                 xsi:noNamespaceSchemaLocation="network-functions.xsd">

	<network-function name="fw-c"  num-ports="2" summary="iptables based firewall">
		<docker uri="firewall-client"/>
	</network-function>
   
	<network-function name="sw-c"  num-ports="3" summary="ovs switch">
		<docker uri="switch--client"/>
	</network-function>

	<network-function name="dhcp-c"  num-ports="1" summary="dhcp server">
		<docker uri="dhcp-client"/>
	</network-function>

	<network-function name="mnt-c"  num-ports="2" summary="ntop based monitor">
		<docker uri="monitor-client"/>
	</network-function>

	<network-function name="nat-c"  num-ports="2" summary="iptables based nat">
		<docker uri="nat-client"/>
	</network-function>

	<network-function name="sw-i"  num-ports="3" summary="ovs switch">
		<docker uri="switch-isp"/>
	</network-function>

	<network-function name="dhcp-i"  num-ports="1" summary="dhcp server">
		<docker uri="dhcp-isp"/>
	</network-function>

	<network-function name="mnt-i"  num-ports="2" summary="ntop based monitor">
		<docker uri="monitor-isp"/>
	</network-function>

	<network-function name="nat-i"  num-ports="2" summary="iptables based nat">
		<docker uri="nat-isp"/>
	</network-function>

</network-functions>
